<?php

namespace Database\Seeders\Dashboard;

use App\Models\Neighborhood;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class NeighborhoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Neighborhood::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $neighborhoods = array(

            //Jerusalem
            array('city_id' => 1, 'name' => array('en' => 'Jerusalem (Beit al-Maqdis)', 'ar' => 'القدس (بيت المقدس)'), 'postal_code' => 'P100'),
            array('city_id' => 1, 'name' => array('en' => 'Jerusalem (Beit al-Maqdis)', 'ar' => 'القدس (بيت المقدس)'), 'postal_code' => 'P101'),
            array('city_id' => 1, 'name' => array('en' => 'Jerusalem (Beit al-Maqdis)', 'ar' => 'القدس (بيت المقدس)'), 'postal_code' => 'P102'),
            array('city_id' => 1, 'name' => array('en' => 'Jerusalem (Beit al-Maqdis)', 'ar' => 'القدس (بيت المقدس)'), 'postal_code' => 'P103'),
            array('city_id' => 1, 'name' => array('en' => 'Jerusalem (Beit al-Maqdis)', 'ar' => 'القدس (بيت المقدس)'), 'postal_code' => 'P104'),
            array('city_id' => 1, 'name' => array('en' => 'Silwan', 'ar' => 'سلوان'), 'postal_code' => 'P107'),
            array('city_id' => 1, 'name' => array('en' => 'Ath-Thuri', 'ar' => 'الثوري'), 'postal_code' => 'P108'),
            array('city_id' => 1, 'name' => array('en' => 'Jabal al-Mukabbir', 'ar' => 'جبل المكبر'), 'postal_code' => 'P109'),
            array('city_id' => 1, 'name' => array('en' => 'Bedou', 'ar' => 'بدو'), 'postal_code' => 'P110'),
            array('city_id' => 1, 'name' => array('en' => 'Beit Surik', 'ar' => 'بيت سوريك'), 'postal_code' => 'P111'),
            array('city_id' => 1, 'name' => array('en' => 'Beit Iksa', 'ar' => 'بيت اكسا'), 'postal_code' => 'P112'),
            array('city_id' => 1, 'name' => array('en' => 'Beit Hanina', 'ar' => 'بيت حنينا'), 'postal_code' => 'P113'),
            array('city_id' => 1, 'name' => array('en' => 'Nabi Samwil', 'ar' => 'النبي صموئيل'), 'postal_code' => 'P113'),
            array('city_id' => 1, 'name' => array('en' => 'Al-Jib', 'ar' => 'الجيب'), 'postal_code' => 'P114'),
            array('city_id' => 1, 'name' => array('en' => 'Beit Ijza', 'ar' => 'بيت إجزا'), 'postal_code' => 'P115'),
            array('city_id' => 1, 'name' => array('en' => 'Al-Qubeiba', 'ar' => 'القبيبة'), 'postal_code' => 'P116'),
            array('city_id' => 1, 'name' => array('en' => 'Beit Duqqu', 'ar' => 'بيت دقو'), 'postal_code' => 'P117'),
            array('city_id' => 1, 'name' => array('en' => 'Beit Anan', 'ar' => 'بيت عنان'), 'postal_code' => 'P118'),
            array('city_id' => 1, 'name' => array('en' => 'Qatanna', 'ar' => 'قطنه'), 'postal_code' => 'P119'),
            array('city_id' => 1, 'name' => array('en' => 'Khirbet Umm al-Lahm', 'ar' => 'خرائب أم اللحم'), 'postal_code' => 'P119'),
            array('city_id' => 1, 'name' => array('en' => 'Beit Hanina (new)', 'ar' => 'بيت حنينا'), 'postal_code' => 'P120'),
            array('city_id' => 1, 'name' => array('en' => 'Bir Nabala', 'ar' => 'بير نبالا'), 'postal_code' => 'P121'),
            array('city_id' => 1, 'name' => array('en' => 'Qalandiya', 'ar' => 'قلنديا'), 'postal_code' => 'P122'),
            array('city_id' => 1, 'name' => array('en' => 'Al-Judayra', 'ar' => 'الجديرة'), 'postal_code' => 'P122'),
            array('city_id' => 1, 'name' => array('en' => 'Rafat', 'ar' => 'رافات'), 'postal_code' => 'P123'),
            array('city_id' => 1, 'name' => array('en' => 'Kafr Aqab', 'ar' => 'كفر عقب'), 'postal_code' => 'P124'),
            array('city_id' => 1, 'name' => array('en' => 'Qalandiya Camp', 'ar' => 'مخيم قلنديا'), 'postal_code' => 'P125'),
            array('city_id' => 1, 'name' => array('en' => 'Al-Ram & Dahiyat al-Barid', 'ar' => 'الرام وضاحية البريد'), 'postal_code' => 'P126'),
            array('city_id' => 1, 'name' => array('en' => 'Mikhmas', 'ar' => 'مخماس'), 'postal_code' => 'P127'),
            array('city_id' => 1, 'name' => array('en' => 'Jaba Bedouin', 'ar' => 'جبع (تجمع بدوي)'), 'postal_code' => 'P128'),
            array('city_id' => 1, 'name' => array('en' => 'Jaba', 'ar' => 'جبع'), 'postal_code' => 'P128'),
            array('city_id' => 1, 'name' => array('en' => 'Hizma', 'ar' => 'حزما'), 'postal_code' => 'P129'),
            array('city_id' => 1, 'name' => array('en' => 'Shuafat', 'ar' => 'شعفاط'), 'postal_code' => 'P130'),
            array('city_id' => 1, 'name' => array('en' => 'Anata', 'ar' => 'عناتا'), 'postal_code' => 'P130'),
            array('city_id' => 1, 'name' => array('en' => 'Shuafat (duplicate)', 'ar' => 'شعفاط'), 'postal_code' => 'P131'),
            array('city_id' => 1, 'name' => array('en' => 'Shuafat Camp', 'ar' => 'مخيم شعفاط'), 'postal_code' => 'P133'),
            array('city_id' => 1, 'name' => array('en' => 'Anata (duplicate)', 'ar' => 'عناتا'), 'postal_code' => 'P134'),
            array('city_id' => 1, 'name' => array('en' => 'Al-Kaabneh Bedouin', 'ar' => 'الكعابنه (تجمع بدوي)'), 'postal_code' => 'P135'),
            array('city_id' => 1, 'name' => array('en' => 'Al-Eizariya', 'ar' => 'العيسوية'), 'postal_code' => 'P137'),
            array('city_id' => 1, 'name' => array('en' => 'Az-Zaayyem', 'ar' => 'الزعيم'), 'postal_code' => 'P139'),
            array('city_id' => 1, 'name' => array('en' => 'Al-Eizariya', 'ar' => 'العيزرية'), 'postal_code' => 'P140'),
            array('city_id' => 1, 'name' => array('en' => 'Abu Dis', 'ar' => 'ابو ديس'), 'postal_code' => 'P144'),
            array('city_id' => 1, 'name' => array('en' => 'Arab al-Jahalin', 'ar' => 'عرب الجهالين'), 'postal_code' => 'P144'),
            array('city_id' => 1, 'name' => array('en' => 'Ash-Sharqiya Sawahira', 'ar' => 'السواحرة الشرقية'), 'postal_code' => 'P145'),
            array('city_id' => 1, 'name' => array('en' => 'Sheikh Saad', 'ar' => 'الشيخ سعد'), 'postal_code' => 'P146'),
            array('city_id' => 1, 'name' => array('en' => 'Al-Gharbiya Sawahira', 'ar' => 'السواحرة الغربية'), 'postal_code' => 'P147'),
            array('city_id' => 1, 'name' => array('en' => 'Sur Baher', 'ar' => 'صور باهر'), 'postal_code' => 'P148'),
            array('city_id' => 1, 'name' => array('en' => 'Umm Tuba', 'ar' => 'ام طوبا'), 'postal_code' => 'P148'),
            array('city_id' => 1, 'name' => array('en' => 'Beit Safafa', 'ar' => 'بيت صفافا'), 'postal_code' => 'P149'),
            array('city_id' => 1, 'name' => array('en' => 'Sharafat', 'ar' => 'شرفات'), 'postal_code' => 'P149'),


            // مدينة بيت لحم


            array('city_id' => 2, 'name' => array('en' => 'Bethlehem', 'ar' => 'بيت لحم'), 'postal_code' => 'P150'),
            array('city_id' => 2, 'name' => array('en' => 'Bethlehem', 'ar' => 'بيت لحم'), 'postal_code' => 'P151'),
            array('city_id' => 2, 'name' => array('en' => 'Bethlehem', 'ar' => 'بيت لحم'), 'postal_code' => 'P152'),
            array('city_id' => 2, 'name' => array('en' => 'Bethlehem', 'ar' => 'بيت لحم'), 'postal_code' => 'P153'),
            array('city_id' => 2, 'name' => array('en' => 'Bethlehem', 'ar' => 'بيت لحم'), 'postal_code' => 'P154'),
            array('city_id' => 2, 'name' => array('en' => 'Bethlehem', 'ar' => 'بيت لحم'), 'postal_code' => 'P156'),
            array('city_id' => 2, 'name' => array('en' => 'Bethlehem', 'ar' => 'بيت لحم'), 'postal_code' => 'P157'),
            array('city_id' => 2, 'name' => array('en' => 'Bethlehem', 'ar' => 'بيت لحم'), 'postal_code' => 'P158'),
            array('city_id' => 2, 'name' => array('en' => 'Dheisheh Camp', 'ar' => 'مخيم الدهيشة'), 'postal_code' => 'P159'),
            array('city_id' => 2, 'name' => array('en' => 'Beit Jala', 'ar' => 'بيت جالا'), 'postal_code' => 'P160'),
            array('city_id' => 2, 'name' => array('en' => 'Beit Jala', 'ar' => 'بيت جالا'), 'postal_code' => 'P161'),
            array('city_id' => 2, 'name' => array('en' => 'Khallet Hamameh', 'ar' => 'خلة حمامة'), 'postal_code' => 'P161'),
            array('city_id' => 2, 'name' => array('en' => 'Bir Ouneh', 'ar' => 'بئر عونه'), 'postal_code' => 'P161'),
            array('city_id' => 2, 'name' => array('en' => 'Beit Jala', 'ar' => 'بيت جالا'), 'postal_code' => 'P162'),
            array('city_id' => 2, 'name' => array('en' => 'Beit Jala', 'ar' => 'بيت جالا'), 'postal_code' => 'P163'),
            array('city_id' => 2, 'name' => array('en' => 'Beit Jala', 'ar' => 'بيت جالا'), 'postal_code' => 'P164'),
            array('city_id' => 2, 'name' => array('en' => 'Doha', 'ar' => 'الدوحة'), 'postal_code' => 'P165'),
            array('city_id' => 2, 'name' => array('en' => 'Al Khadr', 'ar' => 'الخصر'), 'postal_code' => 'P167'),
            array('city_id' => 2, 'name' => array('en' => 'Artas', 'ar' => 'إرطاس'), 'postal_code' => 'P169'),
            array('city_id' => 2, 'name' => array('en' => 'Nahhalin', 'ar' => 'نحالين'), 'postal_code' => 'P170'),
            array('city_id' => 2, 'name' => array('en' => 'Wadi an-Nis', 'ar' => 'وادي النيص'), 'postal_code' => 'P172'),
            array('city_id' => 2, 'name' => array('en' => 'Khallet Afana', 'ar' => 'خلة عفانة'), 'postal_code' => 'P172'),
            array('city_id' => 2, 'name' => array('en' => 'Khallet Sakarya', 'ar' => 'خلة سكاريا'), 'postal_code' => 'P173'),
            array('city_id' => 2, 'name' => array('en' => 'Al-Jab‘a', 'ar' => 'الجبعة'), 'postal_code' => 'P174'),
            array('city_id' => 2, 'name' => array('en' => 'Wadi Fukin', 'ar' => 'وادي فوكين'), 'postal_code' => 'P175'),
            array('city_id' => 2, 'name' => array('en' => 'Husan', 'ar' => 'حوسان'), 'postal_code' => 'P176'),
            array('city_id' => 2, 'name' => array('en' => 'Battir', 'ar' => 'بتير'), 'postal_code' => 'P178'),
            array('city_id' => 2, 'name' => array('en' => 'Al-Walaja', 'ar' => 'الولجة'), 'postal_code' => 'P179'),
            array('city_id' => 2, 'name' => array('en' => 'Beit Sahour', 'ar' => 'بيت ساحور'), 'postal_code' => 'P180'),
            array('city_id' => 2, 'name' => array('en' => 'Beit Sahour', 'ar' => 'بيت ساحور'), 'postal_code' => 'P181'),
            array('city_id' => 2, 'name' => array('en' => 'Beit Sahour', 'ar' => 'بيت ساحور'), 'postal_code' => 'P182'),
            array('city_id' => 2, 'name' => array('en' => 'Al-Khass', 'ar' => 'الخاص'), 'postal_code' => 'P183'),
            array('city_id' => 2, 'name' => array('en' => 'Khallet al-Numan', 'ar' => 'خلة النعمان'), 'postal_code' => 'P183'),
            array('city_id' => 2, 'name' => array('en' => 'Dar Salah', 'ar' => 'دار صلاح'), 'postal_code' => 'P183'),
            array('city_id' => 2, 'name' => array('en' => 'Al-Ubeidiya', 'ar' => 'العبيدية'), 'postal_code' => 'P184'),
            array('city_id' => 2, 'name' => array('en' => 'Al-Haddadiya', 'ar' => 'الحدادية'), 'postal_code' => 'P186'),
            array('city_id' => 2, 'name' => array('en' => 'Al-Shawawra', 'ar' => 'الشواورة'), 'postal_code' => 'P186'),
            array('city_id' => 2, 'name' => array('en' => 'Za‘tara', 'ar' => 'زعترة'), 'postal_code' => 'P187'),
            array('city_id' => 2, 'name' => array('en' => 'Jubbet adh-Dhib', 'ar' => 'جبة الذيب'), 'postal_code' => 'P187'),
            array('city_id' => 2, 'name' => array('en' => 'Beit Ta‘mar', 'ar' => 'بيت تعمر'), 'postal_code' => 'P188'),
            array('city_id' => 2, 'name' => array('en' => 'Hindaza', 'ar' => 'هندازة'), 'postal_code' => 'P189'),
            array('city_id' => 2, 'name' => array('en' => 'Beit Fajjar', 'ar' => 'بيت فجار'), 'postal_code' => 'P190'),
            array('city_id' => 2, 'name' => array('en' => 'Marah Ma‘alla', 'ar' => 'مراح معلا'), 'postal_code' => 'P193'),
            array('city_id' => 2, 'name' => array('en' => 'Um Salamuna', 'ar' => 'أم سلمونة'), 'postal_code' => 'P193'),
            array('city_id' => 2, 'name' => array('en' => 'Al-Manshiya', 'ar' => 'المنشية'), 'postal_code' => 'P193'),
            array('city_id' => 2, 'name' => array('en' => 'Marah Rabah', 'ar' => 'مراح رباح'), 'postal_code' => 'P193'),
            array('city_id' => 2, 'name' => array('en' => 'Wadi Rahhal', 'ar' => 'وادي رحال'), 'postal_code' => 'P194'),
            array('city_id' => 2, 'name' => array('en' => 'Jurat ash-Shama‘a', 'ar' => 'جورة الشمعة'), 'postal_code' => 'P194'),
            array('city_id' => 2, 'name' => array('en' => 'Al-Ma‘sara', 'ar' => 'المعصرة'), 'postal_code' => 'P194'),
            array('city_id' => 2, 'name' => array('en' => 'Khallet al-Haddad', 'ar' => 'خلة الحداد'), 'postal_code' => 'P194'),
            array('city_id' => 2, 'name' => array('en' => 'Khallet al-Louza', 'ar' => 'خلة اللوزة'), 'postal_code' => 'P195'),
            array('city_id' => 2, 'name' => array('en' => 'Jannata (Beit Falouh)', 'ar' => 'جناتة (بيت فلوح)'), 'postal_code' => 'P195'),
            array('city_id' => 2, 'name' => array('en' => 'Tuqu‘', 'ar' => 'تقوع'), 'postal_code' => 'P197'),
            array('city_id' => 2, 'name' => array('en' => 'Kisan', 'ar' => 'كيسان'), 'postal_code' => 'P198'),
            array('city_id' => 2, 'name' => array('en' => 'Al-Maniya', 'ar' => 'المنية'), 'postal_code' => 'P198'),
            array('city_id' => 2, 'name' => array('en' => 'Arab ar-Rashayida', 'ar' => 'عرب الرشايدة'), 'postal_code' => 'P199'),

            //جنين

            array('city_id' => 3, 'name' => array('en' => 'Jenin', 'ar' => 'جنين'), 'postal_code' => 'P200'),
            array('city_id' => 3, 'name' => array('en' => 'Jenin', 'ar' => 'جنين'), 'postal_code' => 'P201'),
            array('city_id' => 3, 'name' => array('en' => 'Jenin Camp', 'ar' => 'مخيم جنين'), 'postal_code' => 'P202'),
            array('city_id' => 3, 'name' => array('en' => 'Jenin', 'ar' => 'جنين'), 'postal_code' => 'P203'),
            array('city_id' => 3, 'name' => array('en' => 'Jenin', 'ar' => 'جنين'), 'postal_code' => 'P204'),
            array('city_id' => 3, 'name' => array('en' => 'Wadi Al-Dab\'a', 'ar' => 'وادي الضبع'), 'postal_code' => 'P204'),
            array('city_id' => 3, 'name' => array('en' => 'Jenin', 'ar' => 'جنين'), 'postal_code' => 'P205'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Jameilat', 'ar' => 'الجميلات'), 'postal_code' => 'P205'),
            array('city_id' => 3, 'name' => array('en' => 'Jenin', 'ar' => 'جنين'), 'postal_code' => 'P206'),
            array('city_id' => 3, 'name' => array('en' => 'Jenin', 'ar' => 'جنين'), 'postal_code' => 'P207'),
            array('city_id' => 3, 'name' => array('en' => 'Jenin', 'ar' => 'جنين'), 'postal_code' => 'P208'),
            array('city_id' => 3, 'name' => array('en' => 'Jenin', 'ar' => 'جنين'), 'postal_code' => 'P209'),
            array('city_id' => 3, 'name' => array('en' => 'Yamun', 'ar' => 'اليامون'), 'postal_code' => 'P210'),
            array('city_id' => 3, 'name' => array('en' => 'Yamun', 'ar' => 'اليامون'), 'postal_code' => 'P211'),
            array('city_id' => 3, 'name' => array('en' => 'Yamun', 'ar' => 'اليامون'), 'postal_code' => 'P212'),
            array('city_id' => 3, 'name' => array('en' => 'Yamun', 'ar' => 'اليامون'), 'postal_code' => 'P213'),
            array('city_id' => 3, 'name' => array('en' => 'Kafr Dan', 'ar' => 'كفر دان'), 'postal_code' => 'P214'),
            array('city_id' => 3, 'name' => array('en' => 'Kafr Dan', 'ar' => 'كفر دان'), 'postal_code' => 'P215'),
            array('city_id' => 3, 'name' => array('en' => 'Birqin', 'ar' => 'برقين'), 'postal_code' => 'P216'),
            array('city_id' => 3, 'name' => array('en' => 'Birqin', 'ar' => 'برقين'), 'postal_code' => 'P217'),
            array('city_id' => 3, 'name' => array('en' => 'Kafr Qud', 'ar' => 'كفر قود'), 'postal_code' => 'P218'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Hashimiyya', 'ar' => 'الهاشمية'), 'postal_code' => 'P219'),
            array('city_id' => 3, 'name' => array('en' => 'Qabatiya', 'ar' => 'قباطية'), 'postal_code' => 'P220'),
            array('city_id' => 3, 'name' => array('en' => 'Qabatiya', 'ar' => 'قباطية'), 'postal_code' => 'P221'),
            array('city_id' => 3, 'name' => array('en' => 'Qabatiya', 'ar' => 'قباطية'), 'postal_code' => 'P222'),
            array('city_id' => 3, 'name' => array('en' => 'Qabatiya', 'ar' => 'قباطية'), 'postal_code' => 'P223'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Shuhada', 'ar' => 'الشهداء'), 'postal_code' => 'P226'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Zababida', 'ar' => 'الزبابدة'), 'postal_code' => 'P227'),
            array('city_id' => 3, 'name' => array('en' => 'Misilya', 'ar' => 'مسلية'), 'postal_code' => 'P228'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Jarba', 'ar' => 'الجربا'), 'postal_code' => 'P229'),
            array('city_id' => 3, 'name' => array('en' => 'Deir Abu Daif', 'ar' => 'دير ابو ضعيف'), 'postal_code' => 'P230'),
            array('city_id' => 3, 'name' => array('en' => 'Deir Abu Daif', 'ar' => 'دير ابو ضعيف'), 'postal_code' => 'P231'),
            array('city_id' => 3, 'name' => array('en' => 'Umm Al-Tut', 'ar' => 'ام التوت'), 'postal_code' => 'P232'),
            array('city_id' => 3, 'name' => array('en' => 'Jalqamous', 'ar' => 'جلقموس'), 'postal_code' => 'P232'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Mughayer', 'ar' => 'المغير'), 'postal_code' => 'P233'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Muttilla', 'ar' => 'المطلة'), 'postal_code' => 'P233'),
            array('city_id' => 3, 'name' => array('en' => 'Jalbun', 'ar' => 'جلبون'), 'postal_code' => 'P234'),
            array('city_id' => 3, 'name' => array('en' => 'Beit Qad', 'ar' => 'بيت قاد'), 'postal_code' => 'P235'),
            array('city_id' => 3, 'name' => array('en' => 'Faqoua', 'ar' => 'فقوعة'), 'postal_code' => 'P236'),
            array('city_id' => 3, 'name' => array('en' => 'Arabouna', 'ar' => 'عربونة'), 'postal_code' => 'P237'),
            array('city_id' => 3, 'name' => array('en' => 'Deir Ghazala', 'ar' => 'دير غزالة'), 'postal_code' => 'P237'),
            array('city_id' => 3, 'name' => array('en' => 'Arana', 'ar' => 'عرانة'), 'postal_code' => 'P238'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Jalama', 'ar' => 'الجلمة'), 'postal_code' => 'P239'),
            array('city_id' => 3, 'name' => array('en' => 'Silat al-Harithiya', 'ar' => 'سيلة الحارثية'), 'postal_code' => 'P240'),
            array('city_id' => 3, 'name' => array('en' => 'Silat al-Harithiya', 'ar' => 'سيلة الحارثية'), 'postal_code' => 'P241'),
            array('city_id' => 3, 'name' => array('en' => 'Kharba Suruj', 'ar' => 'خربة سروج'), 'postal_code' => 'P241'),
            array('city_id' => 3, 'name' => array('en' => 'Tiinik', 'ar' => 'تعنك'), 'postal_code' => 'P243'),
            array('city_id' => 3, 'name' => array('en' => 'Zabouba', 'ar' => 'زبوبه'), 'postal_code' => 'P244'),
            array('city_id' => 3, 'name' => array('en' => 'Rummana', 'ar' => 'رمانة'), 'postal_code' => 'P245'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Sa`ida', 'ar' => 'السعايدة'), 'postal_code' => 'P246'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Taybeh', 'ar' => 'الطيبة'), 'postal_code' => 'P246'),
            array('city_id' => 3, 'name' => array('en' => 'Anin', 'ar' => 'عانين'), 'postal_code' => 'P247'),
            array('city_id' => 3, 'name' => array('en' => 'Zahr al-Malih', 'ar' => 'ظهر المالح'), 'postal_code' => 'P248'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Araqa', 'ar' => 'العرقة'), 'postal_code' => 'P249'),
            array('city_id' => 3, 'name' => array('en' => 'Yabad', 'ar' => 'يعبد'), 'postal_code' => 'P250'),
            array('city_id' => 3, 'name' => array('en' => 'Yabad', 'ar' => 'يعبد'), 'postal_code' => 'P251'),
            array('city_id' => 3, 'name' => array('en' => 'Yabad', 'ar' => 'يعبد'), 'postal_code' => 'P252'),
            array('city_id' => 3, 'name' => array('en' => 'Yabad', 'ar' => 'يعبد'), 'postal_code' => 'P253'),
            array('city_id' => 3, 'name' => array('en' => 'Yabad', 'ar' => 'يعبد'), 'postal_code' => 'P254'),
            array('city_id' => 3, 'name' => array('en' => 'Amriya', 'ar' => 'إمريحة'), 'postal_code' => 'P255'),
            array('city_id' => 3, 'name' => array('en' => 'Zabda', 'ar' => 'زبدة'), 'postal_code' => 'P256'),
            array('city_id' => 3, 'name' => array('en' => 'Khirbet al-Muntar', 'ar' => 'خربة المنطار الغربية'), 'postal_code' => 'P256'),
            array('city_id' => 3, 'name' => array('en' => 'Khirbet al-Muntar', 'ar' => 'خربة المنطار الشرقية'), 'postal_code' => 'P256'),
            array('city_id' => 3, 'name' => array('en' => 'Umm Dar', 'ar' => 'أم دار'), 'postal_code' => 'P256'),
            array('city_id' => 3, 'name' => array('en' => 'Zahr al-Abd', 'ar' => 'ظهر العبد'), 'postal_code' => 'P256'),
            array('city_id' => 3, 'name' => array('en' => 'Khirbet Masoud', 'ar' => 'خربة مسعود (عراق الدوار)'), 'postal_code' => 'P256'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Khuljan', 'ar' => 'الخلجان'), 'postal_code' => 'P256'),
            array('city_id' => 3, 'name' => array('en' => 'Bartaa Sharqiya', 'ar' => 'برطعة الشرقية'), 'postal_code' => 'P257'),
            array('city_id' => 3, 'name' => array('en' => 'Bartaa Sharqiya', 'ar' => 'برطعة الشرقية'), 'postal_code' => 'P258'),
            array('city_id' => 3, 'name' => array('en' => 'Umm al-Rihan', 'ar' => 'أم الريحان'), 'postal_code' => 'P258'),
            array('city_id' => 3, 'name' => array('en' => 'Tura Gharebiya', 'ar' => 'طورة الغربية'), 'postal_code' => 'P259'),
            array('city_id' => 3, 'name' => array('en' => 'Tura Sharqiya', 'ar' => 'طورة الشرقية'), 'postal_code' => 'P259'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Tarim', 'ar' => 'الطرم'), 'postal_code' => 'P259'),
            array('city_id' => 3, 'name' => array('en' => 'Nazlat Sheikh Zaid', 'ar' => 'نزلة الشيخ زيد'), 'postal_code' => 'P259'),
            array('city_id' => 3, 'name' => array('en' => 'Araba', 'ar' => 'عرابة'), 'postal_code' => 'P260'),
            array('city_id' => 3, 'name' => array('en' => 'Arraba', 'ar' => 'عرابة'), 'postal_code' => 'P261'),
            array('city_id' => 3, 'name' => array('en' => 'Arraba', 'ar' => 'عرابة'), 'postal_code' => 'P262'),
            array('city_id' => 3, 'name' => array('en' => 'Arraba', 'ar' => 'عرابة'), 'postal_code' => 'P263'),
            array('city_id' => 3, 'name' => array('en' => 'Arraba', 'ar' => 'عرابة'), 'postal_code' => 'P264'),
            array('city_id' => 3, 'name' => array('en' => 'Fahma al-Jadida', 'ar' => 'فحمة الجديدة'), 'postal_code' => 'P264'),
            array('city_id' => 3, 'name' => array('en' => 'Az-Zawiya', 'ar' => 'الزاوية'), 'postal_code' => 'P265'),
            array('city_id' => 3, 'name' => array('en' => 'Wadi Duuq', 'ar' => 'وادي دعوق'), 'postal_code' => 'P265'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Mansura', 'ar' => 'المنصورة'), 'postal_code' => 'P265'),
            array('city_id' => 3, 'name' => array('en' => 'Marka', 'ar' => 'مركة'), 'postal_code' => 'P266'),
            array('city_id' => 3, 'name' => array('en' => 'Bir al-Basha', 'ar' => 'بير الباشا'), 'postal_code' => 'P267'),
            array('city_id' => 3, 'name' => array('en' => 'Hafirat Arraba', 'ar' => 'الحفيرة (حفيرة عرابه)'), 'postal_code' => 'P267'),
            array('city_id' => 3, 'name' => array('en' => 'Arraba (includes Al-Dhamayra)', 'ar' => 'عرابة تشمل الضمايرة'), 'postal_code' => 'P268'),
            array('city_id' => 3, 'name' => array('en' => 'Kufeirit', 'ar' => 'كفيرت'), 'postal_code' => 'P269'),
            array('city_id' => 3, 'name' => array('en' => 'Kafr Rai', 'ar' => 'كفر راعي'), 'postal_code' => 'P270'),
            array('city_id' => 3, 'name' => array('en' => 'Kafr Rai', 'ar' => 'كفر راعي'), 'postal_code' => 'P271'),
            array('city_id' => 3, 'name' => array('en' => 'Kafr Rai', 'ar' => 'كفر راعي'), 'postal_code' => 'P272'),
            array('city_id' => 3, 'name' => array('en' => 'Fahma', 'ar' => 'فحمة'), 'postal_code' => 'P275'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Rama', 'ar' => 'الرامة'), 'postal_code' => 'P276'),
            array('city_id' => 3, 'name' => array('en' => 'Ajja', 'ar' => 'عجة'), 'postal_code' => 'P278'),
            array('city_id' => 3, 'name' => array('en' => 'Anza', 'ar' => 'عنزة'), 'postal_code' => 'P279'),
            array('city_id' => 3, 'name' => array('en' => 'Jaba', 'ar' => 'جبع'), 'postal_code' => 'P280'),
            array('city_id' => 3, 'name' => array('en' => 'Jaba', 'ar' => 'جبع'), 'postal_code' => 'P281'),
            array('city_id' => 3, 'name' => array('en' => 'Jaba', 'ar' => 'جبع'), 'postal_code' => 'P282'),
            array('city_id' => 3, 'name' => array('en' => 'Sanur', 'ar' => 'صانور'), 'postal_code' => 'P283'),
            array('city_id' => 3, 'name' => array('en' => 'Sanur', 'ar' => 'صانور'), 'postal_code' => 'P284'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Fandaqumiya', 'ar' => 'الفندقومية'), 'postal_code' => 'P285'),
            array('city_id' => 3, 'name' => array('en' => 'Silat adh-Dhahr', 'ar' => 'سيلة الظهر'), 'postal_code' => 'P286'),
            array('city_id' => 3, 'name' => array('en' => 'Silat adh-Dhahr', 'ar' => 'سيلة الظهر'), 'postal_code' => 'P287'),
            array('city_id' => 3, 'name' => array('en' => 'Silat adh-Dhahr', 'ar' => 'سيلة الظهر'), 'postal_code' => 'P288'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Atara', 'ar' => 'العطارة'), 'postal_code' => 'P289'),
            array('city_id' => 3, 'name' => array('en' => 'Meithalun', 'ar' => 'ميثلون'), 'postal_code' => 'P290'),
            array('city_id' => 3, 'name' => array('en' => 'Meithalun', 'ar' => 'ميثلون'), 'postal_code' => 'P291'),
            array('city_id' => 3, 'name' => array('en' => 'Siris', 'ar' => 'سيريس'), 'postal_code' => 'P293'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Judeida', 'ar' => 'الجديدة'), 'postal_code' => 'P295'),
            array('city_id' => 3, 'name' => array('en' => 'Sir', 'ar' => 'صير'), 'postal_code' => 'P296'),
            array('city_id' => 3, 'name' => array('en' => 'Al-Kufeir', 'ar' => 'الكفير'), 'postal_code' => 'P297'),
            array('city_id' => 3, 'name' => array('en' => 'Telfit', 'ar' => 'تلفيت'), 'postal_code' => 'P298'),
            array('city_id' => 3, 'name' => array('en' => 'Raba', 'ar' => 'رابا'), 'postal_code' => 'P299'),




            // طولكرم


            array('city_id' => 4, 'name' => array('en' => 'Tulkarm', 'ar' => 'طولكرم'), 'postal_code' => 'P300'),
            array('city_id' => 4, 'name' => array('en' => 'Tulkarm', 'ar' => 'طولكرم'), 'postal_code' => 'P301'),
            array('city_id' => 4, 'name' => array('en' => 'Tulkarm', 'ar' => 'طولكرم'), 'postal_code' => 'P302'),
            array('city_id' => 4, 'name' => array('en' => 'Tulkarm', 'ar' => 'طولكرم'), 'postal_code' => 'P304'),
            array('city_id' => 4, 'name' => array('en' => 'Tulkarm Camp', 'ar' => 'مخيم طولكرم'), 'postal_code' => 'P304'),
            array('city_id' => 4, 'name' => array('en' => 'Tulkarm', 'ar' => 'طولكرم'), 'postal_code' => 'P305'),
            array('city_id' => 4, 'name' => array('en' => 'Iktaba', 'ar' => 'إكتابا'), 'postal_code' => 'P305'),
            array('city_id' => 4, 'name' => array('en' => 'Tulkarm', 'ar' => 'طولكرم'), 'postal_code' => 'P306'),
            array('city_id' => 4, 'name' => array('en' => 'Iktaba', 'ar' => 'إكتابا'), 'postal_code' => 'P306'),
            array('city_id' => 4, 'name' => array('en' => 'Tulkarm', 'ar' => 'طولكرم'), 'postal_code' => 'P307'),
            array('city_id' => 4, 'name' => array('en' => 'Tulkarm', 'ar' => 'طولكرم'), 'postal_code' => 'P308'),
            array('city_id' => 4, 'name' => array('en' => 'Tulkarm', 'ar' => 'طولكرم'), 'postal_code' => 'P309'),
            array('city_id' => 4, 'name' => array('en' => 'Attil', 'ar' => 'عتيل'), 'postal_code' => 'P310'),
            array('city_id' => 4, 'name' => array('en' => 'Zeita', 'ar' => 'زيتا'), 'postal_code' => 'P311'),
            array('city_id' => 4, 'name' => array('en' => 'Allar', 'ar' => 'علار'), 'postal_code' => 'P313'),
            array('city_id' => 4, 'name' => array('en' => 'Saida', 'ar' => 'صيدا'), 'postal_code' => 'P314'),
            array('city_id' => 4, 'name' => array('en' => 'Eastern Nazlat', 'ar' => 'النزلة الشرقية'), 'postal_code' => 'P315'),
            array('city_id' => 4, 'name' => array('en' => 'Middle Nazlat', 'ar' => 'النزلة الوسطى'), 'postal_code' => 'P315'),
            array('city_id' => 4, 'name' => array('en' => 'Western Nazlat', 'ar' => 'النزلة الغربية'), 'postal_code' => 'P315'),
            array('city_id' => 4, 'name' => array('en' => 'Eastern Baqa', 'ar' => 'باقة الشرقية'), 'postal_code' => 'P316'),
            array('city_id' => 4, 'name' => array('en' => 'Nazlat Isa', 'ar' => 'نزلة عيسى'), 'postal_code' => 'P317'),
            array('city_id' => 4, 'name' => array('en' => 'Qaffin', 'ar' => 'قفين'), 'postal_code' => 'P318'),
            array('city_id' => 4, 'name' => array('en' => 'Akkaba', 'ar' => 'عكابة'), 'postal_code' => 'P319'),
            array('city_id' => 4, 'name' => array('en' => 'Anabta', 'ar' => 'عنبتا'), 'postal_code' => 'P320'),
            array('city_id' => 4, 'name' => array('en' => 'Anabta', 'ar' => 'عنبتا'), 'postal_code' => 'P321'),
            array('city_id' => 4, 'name' => array('en' => 'Bal‘a', 'ar' => 'بلعا'), 'postal_code' => 'P322'),
            array('city_id' => 4, 'name' => array('en' => 'Deir al-Ghusun', 'ar' => 'دير الغصون'), 'postal_code' => 'P324'),
            array('city_id' => 4, 'name' => array('en' => 'Jarushiya', 'ar' => 'الجاروشية'), 'postal_code' => 'P325'),
            array('city_id' => 4, 'name' => array('en' => 'Masqufa', 'ar' => 'المسقوفة'), 'postal_code' => 'P325'),
            array('city_id' => 4, 'name' => array('en' => 'Nur Shams Camp', 'ar' => 'مخيم نور شمس'), 'postal_code' => 'P326'),
            array('city_id' => 4, 'name' => array('en' => 'Iktaba', 'ar' => 'إكتابا'), 'postal_code' => 'P327'),
            array('city_id' => 4, 'name' => array('en' => 'Kafr al-Labad', 'ar' => 'كفر اللبد'), 'postal_code' => 'P328'),
            array('city_id' => 4, 'name' => array('en' => 'Ramin', 'ar' => 'رامين'), 'postal_code' => 'P329'),
            array('city_id' => 4, 'name' => array('en' => 'Beit Lid', 'ar' => 'بيت ليد'), 'postal_code' => 'P330'),
            array('city_id' => 4, 'name' => array('en' => 'Saffarin', 'ar' => 'سفارين'), 'postal_code' => 'P332'),
            array('city_id' => 4, 'name' => array('en' => 'Shufa', 'ar' => 'شوفة'), 'postal_code' => 'P333'),
            array('city_id' => 4, 'name' => array('en' => 'Kafa', 'ar' => 'كفا'), 'postal_code' => 'P333'),
            array('city_id' => 4, 'name' => array('en' => 'Far‘un', 'ar' => 'فرعون'), 'postal_code' => 'P334'),
            array('city_id' => 4, 'name' => array('en' => 'Khirbet Jubara', 'ar' => 'خربة جبارة'), 'postal_code' => 'P334'),
            array('city_id' => 4, 'name' => array('en' => 'Kafr Sur', 'ar' => 'كفر صور'), 'postal_code' => 'P336'),
            array('city_id' => 4, 'name' => array('en' => 'Kour', 'ar' => 'كور'), 'postal_code' => 'P336'),
            array('city_id' => 4, 'name' => array('en' => 'Al-Ras', 'ar' => 'الراس'), 'postal_code' => 'P336'),
            array('city_id' => 4, 'name' => array('en' => 'Kafr Abbush', 'ar' => 'كفر عبوش'), 'postal_code' => 'P337'),
            array('city_id' => 4, 'name' => array('en' => 'Kafr Zibad', 'ar' => 'كفر زيباد'), 'postal_code' => 'P338'),
            array('city_id' => 4, 'name' => array('en' => 'Kafr Jamal', 'ar' => 'كفر جمال'), 'postal_code' => 'P339'),

            // قلقيلية


            array('city_id' => 5, 'name' => array('en' => 'Qalqilya', 'ar' => 'قلقيلية'), 'postal_code' => 'P340'),
            array('city_id' => 5, 'name' => array('en' => 'Qalqilya', 'ar' => 'قلقيلية'), 'postal_code' => 'P342'),
            array('city_id' => 5, 'name' => array('en' => 'Qalqilya', 'ar' => 'قلقيلية'), 'postal_code' => 'P343'),
            array('city_id' => 5, 'name' => array('en' => 'Qalqilya', 'ar' => 'قلقيلية'), 'postal_code' => 'P344'),
            array('city_id' => 5, 'name' => array('en' => 'Qalqilya', 'ar' => 'قلقيلية'), 'postal_code' => 'P345'),
            array('city_id' => 5, 'name' => array('en' => 'Qalqilya', 'ar' => 'قلقيلية'), 'postal_code' => 'P346'),
            array('city_id' => 5, 'name' => array('en' => 'Qalqilya', 'ar' => 'قلقيلية'), 'postal_code' => 'P347'),
            array('city_id' => 5, 'name' => array('en' => 'Qalqilya', 'ar' => 'قلقيلية'), 'postal_code' => 'P348'),
            array('city_id' => 5, 'name' => array('en' => 'Qalqilya', 'ar' => 'قلقيلية'), 'postal_code' => 'P349'),
            array('city_id' => 5, 'name' => array('en' => 'Azzun', 'ar' => 'عزون'), 'postal_code' => 'P350'),
            array('city_id' => 5, 'name' => array('en' => 'Arab al-Khouleh', 'ar' => 'عرب الخوله'), 'postal_code' => 'P350'),
            array('city_id' => 5, 'name' => array('en' => 'Khirbet Sir', 'ar' => 'خربة صير'), 'postal_code' => 'P352'),
            array('city_id' => 5, 'name' => array('en' => 'Jayyous', 'ar' => 'جيوس'), 'postal_code' => 'P353'),
            array('city_id' => 5, 'name' => array('en' => 'Falamya', 'ar' => 'فلامية'), 'postal_code' => 'P354'),
            array('city_id' => 5, 'name' => array('en' => 'North Arab ar-Ramadin', 'ar' => 'عرب الرماضين الشمالي'), 'postal_code' => 'P355'),
            array('city_id' => 5, 'name' => array('en' => 'Izbat at-Tabib', 'ar' => 'عزبة الطبيب'), 'postal_code' => 'P357'),
            array('city_id' => 5, 'name' => array('en' => 'Asla', 'ar' => 'عسلة'), 'postal_code' => 'P357'),
            array('city_id' => 5, 'name' => array('en' => 'Nabi Ilyas', 'ar' => 'النبي إلياس'), 'postal_code' => 'P358'),
            array('city_id' => 5, 'name' => array('en' => 'South Arab ar-Ramadin', 'ar' => 'عرب الرماضين الجنوبي'), 'postal_code' => 'P359'),
            array('city_id' => 5, 'name' => array('en' => 'Habla', 'ar' => 'حبلة'), 'postal_code' => 'P360'),
            array('city_id' => 5, 'name' => array('en' => 'Ras Atiya', 'ar' => 'راس عطية'), 'postal_code' => 'P361'),
            array('city_id' => 5, 'name' => array('en' => 'Wadi ar-Rasha', 'ar' => 'وادي الرشا'), 'postal_code' => 'P362'),
            array('city_id' => 5, 'name' => array('en' => 'Ras at-Tira', 'ar' => 'راس الطيرة'), 'postal_code' => 'P362'),
            array('city_id' => 5, 'name' => array('en' => 'ad-Daba', 'ar' => 'الضبعة'), 'postal_code' => 'P362'),
            array('city_id' => 5, 'name' => array('en' => 'Izbat Jaloud', 'ar' => 'عزبة جلعود'), 'postal_code' => 'P363'),
            array('city_id' => 5, 'name' => array('en' => 'Izbat Salman', 'ar' => 'عزبة سلمان'), 'postal_code' => 'P363'),
            array('city_id' => 5, 'name' => array('en' => 'Izbat al-Ashqar', 'ar' => 'عزبة الأشقر'), 'postal_code' => 'P364'),
            array('city_id' => 5, 'name' => array('en' => 'al-Mudawwar', 'ar' => 'المدور'), 'postal_code' => 'P364'),
            array('city_id' => 5, 'name' => array('en' => 'Kafr Thulth', 'ar' => 'كفر ثلث'), 'postal_code' => 'P366'),
            array('city_id' => 5, 'name' => array('en' => 'Sanniriya', 'ar' => 'سنيريا'), 'postal_code' => 'P367'),
            array('city_id' => 5, 'name' => array('en' => 'Beit Amin', 'ar' => 'بيت أمين'), 'postal_code' => 'P368'),
            array('city_id' => 5, 'name' => array('en' => 'Azzun Atma', 'ar' => 'عزون عتمة'), 'postal_code' => 'P369'),
            array('city_id' => 5, 'name' => array('en' => 'Kafr Qaddum', 'ar' => 'كفر قدوم'), 'postal_code' => 'P370'),
            array('city_id' => 5, 'name' => array('en' => 'Jit', 'ar' => 'جيت'), 'postal_code' => 'P371'),
            array('city_id' => 5, 'name' => array('en' => 'Far‘ata', 'ar' => 'فرعتا'), 'postal_code' => 'P372'),
            array('city_id' => 5, 'name' => array('en' => 'Immatin', 'ar' => 'إماتين'), 'postal_code' => 'P373'),
            array('city_id' => 5, 'name' => array('en' => 'al-Funduq', 'ar' => 'الفندق'), 'postal_code' => 'P374'),
            array('city_id' => 5, 'name' => array('en' => 'Jinsafut', 'ar' => 'جنصافوط'), 'postal_code' => 'P375'),
            array('city_id' => 5, 'name' => array('en' => 'Kafr Laqif', 'ar' => 'كفر لاقف'), 'postal_code' => 'P376'),
            array('city_id' => 5, 'name' => array('en' => 'Baqat al-Hatab', 'ar' => 'باقة الحطب'), 'postal_code' => 'P377'),


            // سلفيت



            array('city_id' => 6, 'name' => array('en' => 'Biddya', 'ar' => 'بديا'), 'postal_code' => 'P380'),
            array('city_id' => 6, 'name' => array('en' => 'Mas-ha', 'ar' => 'مسحة'), 'postal_code' => 'P382'),
            array('city_id' => 6, 'name' => array('en' => 'az-Zawiya', 'ar' => 'الزاوية'), 'postal_code' => 'P383'),
            array('city_id' => 6, 'name' => array('en' => 'Rafat', 'ar' => 'رافات'), 'postal_code' => 'P384'),
            array('city_id' => 6, 'name' => array('en' => 'Deir Ballut', 'ar' => 'دير بلوط'), 'postal_code' => 'P385'),
            array('city_id' => 6, 'name' => array('en' => 'Sarta', 'ar' => 'صرطة'), 'postal_code' => 'P386'),
            array('city_id' => 6, 'name' => array('en' => 'Qarawat Bani Hassan', 'ar' => 'قراوة بني حسان'), 'postal_code' => 'P387'),
            array('city_id' => 6, 'name' => array('en' => 'Deir Istiya', 'ar' => 'دير إستيا'), 'postal_code' => 'P388'),
            array('city_id' => 6, 'name' => array('en' => 'Salfit', 'ar' => 'سلفيت'), 'postal_code' => 'P390'),
            array('city_id' => 6, 'name' => array('en' => 'Khirbet Qeis', 'ar' => 'خربة قيس'), 'postal_code' => 'P391'),
            array('city_id' => 6, 'name' => array('en' => 'Iskaka', 'ar' => 'إسكاكا'), 'postal_code' => 'P392'),
            array('city_id' => 6, 'name' => array('en' => 'Yasuf', 'ar' => 'ياسوف'), 'postal_code' => 'P392'),
            array('city_id' => 6, 'name' => array('en' => 'Marda', 'ar' => 'مردا'), 'postal_code' => 'P393'),
            array('city_id' => 6, 'name' => array('en' => 'Qira', 'ar' => 'قيرة'), 'postal_code' => 'P394'),
            array('city_id' => 6, 'name' => array('en' => 'Kifl Haris', 'ar' => 'كفل حارس'), 'postal_code' => 'P395'),
            array('city_id' => 6, 'name' => array('en' => 'Haris', 'ar' => 'حارس'), 'postal_code' => 'P396'),
            array('city_id' => 6, 'name' => array('en' => 'Farkha', 'ar' => 'فرخة'), 'postal_code' => 'P397'),
            array('city_id' => 6, 'name' => array('en' => 'Izbet Abu Adam', 'ar' => "'عزبة أبو آدم"), 'postal_code' => 'P398'),
            array('city_id' => 6, 'name' => array('en' => 'Bruqin', 'ar' => 'بروقين'), 'postal_code' => 'P398'),
            array('city_id' => 6, 'name' => array('en' => 'Kafr ad-Dik', 'ar' => 'كفر الديك'), 'postal_code' => 'P399'),

            // نابلس

            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P400'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P401'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P402'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P403'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P404'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P405'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P406'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P407'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P408'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P409'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P410'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P411'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P412'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P413'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P414'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P415'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P416'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P417'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P418'),
            array('city_id' => 7, 'name' => array('en' => 'Ein Beit al-Ma Camp', 'ar' => 'مخيم عين بيت الماء'), 'postal_code' => 'P419'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P420'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P421'),
            array('city_id' => 7, 'name' => array('en' => 'Balata Camp', 'ar' => 'مخيم بلاطة'), 'postal_code' => 'P422'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P423'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P424'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P425'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P426'),
            array('city_id' => 7, 'name' => array('en' => 'Askar Camp', 'ar' => 'مخيم عسكر'), 'postal_code' => 'P427'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P428'),
            array('city_id' => 7, 'name' => array('en' => 'Nablus', 'ar' => 'نابلس'), 'postal_code' => 'P429'),
            array('city_id' => 7, 'name' => array('en' => 'Asira ash-Shamaliya', 'ar' => 'عصيرة الشمالية'), 'postal_code' => 'P430'),
            array('city_id' => 7, 'name' => array('en' => 'Asira ash-Shamaliya', 'ar' => 'عصيرة الشمالية'), 'postal_code' => 'P431'),
            array('city_id' => 7, 'name' => array('en' => 'Yasid', 'ar' => 'ياصيد'), 'postal_code' => 'P432'),
            array('city_id' => 7, 'name' => array('en' => 'Talouza', 'ar' => 'طلوزة'), 'postal_code' => 'P433'),
            array('city_id' => 7, 'name' => array('en' => 'Al-Badhan', 'ar' => 'الباذان'), 'postal_code' => 'P434'),
            array('city_id' => 7, 'name' => array('en' => 'Azmut', 'ar' => 'عزموط'), 'postal_code' => 'P435'),
            array('city_id' => 7, 'name' => array('en' => 'Beit Hasan', 'ar' => 'بيت حسن'), 'postal_code' => 'P438'),
            array('city_id' => 7, 'name' => array('en' => 'Aqrabaniya', 'ar' => 'العقربانية'), 'postal_code' => 'P438'),
            array('city_id' => 7, 'name' => array('en' => 'An-Nassariya', 'ar' => 'النصارية'), 'postal_code' => 'P438'),
            array('city_id' => 7, 'name' => array('en' => 'Ein Shibli', 'ar' => 'عين شبلي'), 'postal_code' => 'P438'),
            array('city_id' => 7, 'name' => array('en' => 'Faroosh Beit Dajan', 'ar' => 'فروش بيت دجن'), 'postal_code' => 'P439'),
            array('city_id' => 7, 'name' => array('en' => 'Burqa', 'ar' => 'برقة'), 'postal_code' => 'P440'),
            array('city_id' => 7, 'name' => array('en' => 'Bizzariya', 'ar' => 'بزاريه'), 'postal_code' => 'P441'),
            array('city_id' => 7, 'name' => array('en' => 'Beit Imrin', 'ar' => 'بيت إمرين'), 'postal_code' => 'P442'),
            array('city_id' => 7, 'name' => array('en' => 'Nisf Jubeil', 'ar' => 'نصف جبيل'), 'postal_code' => 'P443'),
            array('city_id' => 7, 'name' => array('en' => 'Ijjnisinya', 'ar' => 'إجنسنيا'), 'postal_code' => 'P443'),
            array('city_id' => 7, 'name' => array('en' => 'Sebastia', 'ar' => 'سبسطية'), 'postal_code' => 'P444'),
            array('city_id' => 7, 'name' => array('en' => 'Deir Sharaf', 'ar' => 'دير شرف'), 'postal_code' => 'P445'),
            array('city_id' => 7, 'name' => array('en' => 'An-Naqura', 'ar' => 'الناقورة'), 'postal_code' => 'P446'),
            array('city_id' => 7, 'name' => array('en' => 'Zawata', 'ar' => 'زواتا'), 'postal_code' => 'P447'),
            array('city_id' => 7, 'name' => array('en' => 'Beit Wazan', 'ar' => 'بيت وزن'), 'postal_code' => 'P448'),
            array('city_id' => 7, 'name' => array('en' => 'Beit Iba', 'ar' => 'بيت إيبا'), 'postal_code' => 'P448'),
            array('city_id' => 7, 'name' => array('en' => 'Qusin', 'ar' => 'قوصين'), 'postal_code' => 'P449'),
            array('city_id' => 7, 'name' => array('en' => 'Jama\'in', 'ar' => 'جماعين'), 'postal_code' => 'P450'),
            array('city_id' => 7, 'name' => array('en' => 'Jama\'in', 'ar' => 'جماعين'), 'postal_code' => 'P451'),
            array('city_id' => 7, 'name' => array('en' => 'Zita Jama\'in', 'ar' => 'زيتا جماعين'), 'postal_code' => 'P452'),
            array('city_id' => 7, 'name' => array('en' => 'Ainbus', 'ar' => 'عينبوس'), 'postal_code' => 'P453'),
            array('city_id' => 7, 'name' => array('en' => 'Awreef', 'ar' => 'عوريف'), 'postal_code' => 'P454'),
            array('city_id' => 7, 'name' => array('en' => 'Asira al-Qibliya', 'ar' => 'عصيرة القبلية'), 'postal_code' => 'P455'),
            array('city_id' => 7, 'name' => array('en' => 'Madama', 'ar' => 'مادما'), 'postal_code' => 'P456'),
            array('city_id' => 7, 'name' => array('en' => 'Iraq Burin', 'ar' => 'عراق بورين'), 'postal_code' => 'P457'),
            array('city_id' => 7, 'name' => array('en' => 'Tall', 'ar' => 'تل'), 'postal_code' => 'P458'),
            array('city_id' => 7, 'name' => array('en' => 'Sarrah', 'ar' => 'صرة'), 'postal_code' => 'P459'),
            array('city_id' => 7, 'name' => array('en' => 'Beita', 'ar' => 'بيتا'), 'postal_code' => 'P460'),
            array('city_id' => 7, 'name' => array('en' => 'Udayla', 'ar' => 'أودلا'), 'postal_code' => 'P463'),
            array('city_id' => 7, 'name' => array('en' => 'Awarta', 'ar' => 'عورتا'), 'postal_code' => 'P464'),
            array('city_id' => 7, 'name' => array('en' => 'Kafr Qalil', 'ar' => 'كفر قليل'), 'postal_code' => 'P466'),
            array('city_id' => 7, 'name' => array('en' => 'Burin', 'ar' => 'بورين'), 'postal_code' => 'P467'),
            array('city_id' => 7, 'name' => array('en' => 'Huwara', 'ar' => 'حوارة'), 'postal_code' => 'P468'),
            array('city_id' => 7, 'name' => array('en' => 'Huwara', 'ar' => 'حوارة'), 'postal_code' => 'P469'),
            array('city_id' => 7, 'name' => array('en' => 'Beit Furik', 'ar' => 'بيت فوريك'), 'postal_code' => 'P470'),
            array('city_id' => 7, 'name' => array('en' => 'Beit Furik', 'ar' => 'بيت فوريك'), 'postal_code' => 'P471'),
            array('city_id' => 7, 'name' => array('en' => 'Rujib', 'ar' => 'روجيب'), 'postal_code' => 'P473'),
            array('city_id' => 7, 'name' => array('en' => 'Deir al-Hatab', 'ar' => 'دير الحطب'), 'postal_code' => 'P475'),
            array('city_id' => 7, 'name' => array('en' => 'Salim', 'ar' => 'سالم'), 'postal_code' => 'P477'),
            array('city_id' => 7, 'name' => array('en' => 'Beit Dajan', 'ar' => 'بيت دجن'), 'postal_code' => 'P479'),
            array('city_id' => 7, 'name' => array('en' => 'Aqraba', 'ar' => 'عقربا'), 'postal_code' => 'P480'),
            array('city_id' => 7, 'name' => array('en' => 'Yanon', 'ar' => 'يانون'), 'postal_code' => 'P480'),
            array('city_id' => 7, 'name' => array('en' => 'Aqraba', 'ar' => 'عقربا'), 'postal_code' => 'P481'),
            array('city_id' => 7, 'name' => array('en' => 'Rajman', 'ar' => 'الرجمان'), 'postal_code' => 'P481'),
            array('city_id' => 7, 'name' => array('en' => 'Awsarin', 'ar' => 'اوصرين'), 'postal_code' => 'P483'),
            array('city_id' => 7, 'name' => array('en' => 'Jorish', 'ar' => 'جوريش'), 'postal_code' => 'P484'),
            array('city_id' => 7, 'name' => array('en' => 'Qusra', 'ar' => 'قصرة'), 'postal_code' => 'P485'),
            array('city_id' => 7, 'name' => array('en' => 'Jalud', 'ar' => 'جالود'), 'postal_code' => 'P486'),
            array('city_id' => 7, 'name' => array('en' => 'Duma', 'ar' => 'دوما'), 'postal_code' => 'P487'),
            array('city_id' => 7, 'name' => array('en' => 'Majdal Bani Fadel', 'ar' => 'مجدل بني فاضل'), 'postal_code' => 'P488'),
            array('city_id' => 7, 'name' => array('en' => 'Tall al-Khashaba', 'ar' => 'تل الخشبة'), 'postal_code' => 'P489'),
            array('city_id' => 7, 'name' => array('en' => 'Qabalan', 'ar' => 'قبلان'), 'postal_code' => 'P490'),
            array('city_id' => 7, 'name' => array('en' => 'Yitma', 'ar' => 'يتما'), 'postal_code' => 'P493'),
            array('city_id' => 7, 'name' => array('en' => 'Talfit', 'ar' => 'تلفيت'), 'postal_code' => 'P494'),
            array('city_id' => 7, 'name' => array('en' => 'Qaryut', 'ar' => 'قريوت'), 'postal_code' => 'P495'),
            array('city_id' => 7, 'name' => array('en' => 'As-Sawiya', 'ar' => 'الساوية'), 'postal_code' => 'P496'),
            array('city_id' => 7, 'name' => array('en' => 'Al-Lubban Ash-Sharqiya', 'ar' => 'أللبن الشرقية'), 'postal_code' => 'P498'),
            array('city_id' => 7, 'name' => array('en' => 'Amuriyya', 'ar' => 'عمورية'), 'postal_code' => 'P499'),

            //طوباس

            array('city_id' => 8, 'name' => array('en' => 'Tubas', 'ar' => 'طوباس'), 'postal_code' => 'P500'),
            array('city_id' => 8, 'name' => array('en' => 'Tubas', 'ar' => 'طوباس'), 'postal_code' => 'P501'),
            array('city_id' => 8, 'name' => array('en' => 'Tubas', 'ar' => 'طوباس'), 'postal_code' => 'P502'),
            array('city_id' => 8, 'name' => array('en' => 'Tubas', 'ar' => 'طوباس'), 'postal_code' => 'P503'),
            array('city_id' => 8, 'name' => array('en' => 'Tubas', 'ar' => 'طوباس'), 'postal_code' => 'P504'),
            array('city_id' => 8, 'name' => array('en' => 'Tubas', 'ar' => 'طوباس'), 'postal_code' => 'P506'),
            array('city_id' => 8, 'name' => array('en' => 'Tubas', 'ar' => 'طوباس'), 'postal_code' => 'P507'),
            array('city_id' => 8, 'name' => array('en' => 'Tubas', 'ar' => 'طوباس'), 'postal_code' => 'P508'),
            array('city_id' => 8, 'name' => array('en' => 'Al-Thaghra', 'ar' => 'الثغرة'), 'postal_code' => 'P509'),
            array('city_id' => 8, 'name' => array('en' => 'Tubas', 'ar' => 'طوباس'), 'postal_code' => 'P509'),
            array('city_id' => 8, 'name' => array('en' => 'Tayaseer', 'ar' => 'تياسير'), 'postal_code' => 'P509'),
            array('city_id' => 8, 'name' => array('en' => 'Aqabah', 'ar' => 'عقابه'), 'postal_code' => 'P510'),
            array('city_id' => 8, 'name' => array('en' => 'Salhab', 'ar' => 'سلحب'), 'postal_code' => 'P514'),
            array('city_id' => 8, 'name' => array('en' => 'Kashda', 'ar' => 'كشدة'), 'postal_code' => 'P516'),
            array('city_id' => 8, 'name' => array('en' => 'Wadi al-Far\'ah', 'ar' => 'وادي الفارعة'), 'postal_code' => 'P517'),
            array('city_id' => 8, 'name' => array('en' => 'Fara\'ah Refugee Camp', 'ar' => 'مخيم الفارعة'), 'postal_code' => 'P519'),
            array('city_id' => 8, 'name' => array('en' => 'Tayaseer', 'ar' => 'تياسير'), 'postal_code' => 'P520'),
            array('city_id' => 8, 'name' => array('en' => 'Al-Aqaba', 'ar' => 'العقبة'), 'postal_code' => 'P521'),
            array('city_id' => 8, 'name' => array('en' => 'Ibziq', 'ar' => 'إبزيق'), 'postal_code' => 'P522'),
            array('city_id' => 8, 'name' => array('en' => 'Khirbet Yirza', 'ar' => 'خربة يرزة'), 'postal_code' => 'P524'),
            array('city_id' => 8, 'name' => array('en' => 'Al-Malih', 'ar' => 'المالح'), 'postal_code' => 'P525'),
            array('city_id' => 8, 'name' => array('en' => 'Al-Farisiyah', 'ar' => 'الفارسية'), 'postal_code' => 'P526'),
            array('city_id' => 8, 'name' => array('en' => 'Ain al-Bayda', 'ar' => 'عين البيضا'), 'postal_code' => 'P527'),
            array('city_id' => 8, 'name' => array('en' => 'Kardala', 'ar' => 'كردلة'), 'postal_code' => 'P528'),
            array('city_id' => 8, 'name' => array('en' => 'Bardala', 'ar' => 'بردلة'), 'postal_code' => 'P529'),
            array('city_id' => 8, 'name' => array('en' => 'Tammun', 'ar' => 'طمون'), 'postal_code' => 'P530'),
            array('city_id' => 8, 'name' => array('en' => 'Tammoun', 'ar' => 'طمون'), 'postal_code' => 'P533'),
            array('city_id' => 8, 'name' => array('en' => 'Tammoun', 'ar' => 'طمون'), 'postal_code' => 'P534'),
            array('city_id' => 8, 'name' => array('en' => 'Khirbet Ras al-Ahmar', 'ar' => 'خربة الراس الأحمر'), 'postal_code' => 'P536'),
            array('city_id' => 8, 'name' => array('en' => 'Khirbet Humsa', 'ar' => 'خربة حمصة'), 'postal_code' => 'P536'),
            array('city_id' => 8, 'name' => array('en' => 'Khirbet Atoof', 'ar' => 'خربة عاطوف'), 'postal_code' => 'P536'),
            array('city_id' => 8, 'name' => array('en' => 'Tammoun', 'ar' => 'طمون'), 'postal_code' => 'P537'),
            array('city_id' => 8, 'name' => array('en' => 'Tubas', 'ar' => 'طوباس'), 'postal_code' => 'P540'),

            // أريحا

            array('city_id' => 9, 'name' => array('en' => 'Al-Jiftlik', 'ar' => 'الجفتلك'), 'postal_code' => 'P550'),
            array('city_id' => 9, 'name' => array('en' => 'Al-Zubaydah', 'ar' => 'الزبيدات'), 'postal_code' => 'P555'),
            array('city_id' => 9, 'name' => array('en' => 'Marj al-Ghazal', 'ar' => 'مرج الغزال'), 'postal_code' => 'P555'),
            array('city_id' => 9, 'name' => array('en' => 'Marj Na\'jah', 'ar' => 'مرج نعجة'), 'postal_code' => 'P555'),
            array('city_id' => 9, 'name' => array('en' => 'Fasayil', 'ar' => 'فصايل'), 'postal_code' => 'P560'),
            array('city_id' => 9, 'name' => array('en' => 'Al-Awja', 'ar' => 'العوجا'), 'postal_code' => 'P565'),
            array('city_id' => 9, 'name' => array('en' => 'Al-Nuwaima', 'ar' => 'النويعمة'), 'postal_code' => 'P570'),
            array('city_id' => 9, 'name' => array('en' => 'Ain al-Duyuk al-Fouqa', 'ar' => 'عين الديوك الفوقا'), 'postal_code' => 'P573'),
            array('city_id' => 9, 'name' => array('en' => 'Deir al-Qilt', 'ar' => 'دير القلط'), 'postal_code' => 'P573'),
            array('city_id' => 9, 'name' => array('en' => 'Al-Nuwaima', 'ar' => 'النويعمة'), 'postal_code' => 'P576'),
            array('city_id' => 9, 'name' => array('en' => 'Ain al-Sultan Refugee Camp', 'ar' => 'مخيم عين السلطان'), 'postal_code' => 'P578'),
            array('city_id' => 9, 'name' => array('en' => 'Aqabat Jabr Refugee Camp', 'ar' => 'مخيم عقبة جبر'), 'postal_code' => 'P579'),
            array('city_id' => 9, 'name' => array('en' => 'Ariha', 'ar' => 'أريحا'), 'postal_code' => 'P580'),
            array('city_id' => 9, 'name' => array('en' => 'Ariha', 'ar' => 'أريحا'), 'postal_code' => 'P581'),
            array('city_id' => 9, 'name' => array('en' => 'Ariha', 'ar' => 'أريحا'), 'postal_code' => 'P582'),
            array('city_id' => 9, 'name' => array('en' => 'Ariha', 'ar' => 'أريحا'), 'postal_code' => 'P583'),
            array('city_id' => 9, 'name' => array('en' => 'Ariha', 'ar' => 'أريحا'), 'postal_code' => 'P584'),
            array('city_id' => 9, 'name' => array('en' => 'Ariha', 'ar' => 'أريحا'), 'postal_code' => 'P585'),
            array('city_id' => 9, 'name' => array('en' => 'Ariha', 'ar' => 'أريحا'), 'postal_code' => 'P586'),
            array('city_id' => 9, 'name' => array('en' => 'Ariha', 'ar' => 'أريحا'), 'postal_code' => 'P587'),
            array('city_id' => 9, 'name' => array('en' => 'Ariha', 'ar' => 'أريحا'), 'postal_code' => 'P588'),
            array('city_id' => 9, 'name' => array('en' => 'Ariha', 'ar' => 'أريحا'), 'postal_code' => 'P589'),
            array('city_id' => 9, 'name' => array('en' => 'Nabi Musa', 'ar' => 'النبي موسى'), 'postal_code' => 'P590'),
            array('city_id' => 9, 'name' => array('en' => 'Deir Hajjla', 'ar' => 'دير حجلة'), 'postal_code' => 'P590'),


            //رام الله والبيرة


            array('city_id' => 10, 'name' => array('en' => 'Ramallah', 'ar' => 'رام الله'), 'postal_code' => 'P600'),
            array('city_id' => 10, 'name' => array('en' => 'Ramallah', 'ar' => 'رام الله'), 'postal_code' => 'P601'),
            array('city_id' => 10, 'name' => array('en' => 'Ramallah', 'ar' => 'رام الله'), 'postal_code' => 'P602'),
            array('city_id' => 10, 'name' => array('en' => 'Ramallah', 'ar' => 'رام الله'), 'postal_code' => 'P603'),
            array('city_id' => 10, 'name' => array('en' => 'Ramallah', 'ar' => 'رام الله'), 'postal_code' => 'P604'),
            array('city_id' => 10, 'name' => array('en' => 'Ramallah', 'ar' => 'رام الله'), 'postal_code' => 'P605'),
            array('city_id' => 10, 'name' => array('en' => 'Ramallah', 'ar' => 'رام الله'), 'postal_code' => 'P606'),
            array('city_id' => 10, 'name' => array('en' => 'Ramallah', 'ar' => 'رام الله'), 'postal_code' => 'P607'),
            array('city_id' => 10, 'name' => array('en' => 'Ramallah', 'ar' => 'رام الله'), 'postal_code' => 'P608'),
            array('city_id' => 10, 'name' => array('en' => 'Ramallah', 'ar' => 'رام الله'), 'postal_code' => 'P609'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Bireh', 'ar' => 'البيرة'), 'postal_code' => 'P610'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Bireh', 'ar' => 'البيرة'), 'postal_code' => 'P611'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Bireh', 'ar' => 'البيرة'), 'postal_code' => 'P612'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Bireh', 'ar' => 'البيرة'), 'postal_code' => 'P613'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Bireh', 'ar' => 'البيرة'), 'postal_code' => 'P614'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Bireh', 'ar' => 'البيرة'), 'postal_code' => 'P615'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Bireh', 'ar' => 'البيرة'), 'postal_code' => 'P616'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Bireh', 'ar' => 'البيرة'), 'postal_code' => 'P617'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Bireh', 'ar' => 'البيرة'), 'postal_code' => 'P618'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Bireh', 'ar' => 'البيرة'), 'postal_code' => 'P619'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Zaytuna', 'ar' => 'الزيتونة'), 'postal_code' => 'P620'),
            array('city_id' => 10, 'name' => array('en' => 'Abu Qash', 'ar' => 'ابو قش'), 'postal_code' => 'P622'),
            array('city_id' => 10, 'name' => array('en' => 'Sarda', 'ar' => 'صردا'), 'postal_code' => 'P623'),
            array('city_id' => 10, 'name' => array('en' => 'Dura al-Qari\'', 'ar' => 'دورا القرع'), 'postal_code' => 'P624'),
            array('city_id' => 10, 'name' => array('en' => 'Jalzon Refugee Camp', 'ar' => 'مخيم الجلزون'), 'postal_code' => 'P625'),
            array('city_id' => 10, 'name' => array('en' => 'Jifna', 'ar' => 'جفنا'), 'postal_code' => 'P626'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Duheh', 'ar' => 'الدوحة'), 'postal_code' => 'P626'),
            array('city_id' => 10, 'name' => array('en' => 'Bir Zeit', 'ar' => 'بير زيت'), 'postal_code' => 'P627'),
            array('city_id' => 10, 'name' => array('en' => 'Ain Siniya', 'ar' => 'عين سينيا'), 'postal_code' => 'P628'),
            array('city_id' => 10, 'name' => array('en' => 'Yabrud', 'ar' => 'يبرود'), 'postal_code' => 'P629'),
            array('city_id' => 10, 'name' => array('en' => 'Beitunia', 'ar' => 'بيتونيا'), 'postal_code' => 'P630'),
            array('city_id' => 10, 'name' => array('en' => 'Beitunia', 'ar' => 'بيتونيا'), 'postal_code' => 'P631'),
            array('city_id' => 10, 'name' => array('en' => 'Beitunia', 'ar' => 'بيتونيا'), 'postal_code' => 'P632'),
            array('city_id' => 10, 'name' => array('en' => 'Beitunia', 'ar' => 'بيتونيا'), 'postal_code' => 'P633'),
            array('city_id' => 10, 'name' => array('en' => 'Beitunia', 'ar' => 'بيتونيا'), 'postal_code' => 'P634'),
            array('city_id' => 10, 'name' => array('en' => 'Ain Qinya', 'ar' => 'عين قينيا'), 'postal_code' => 'P636'),
            array('city_id' => 10, 'name' => array('en' => 'Ain Arik', 'ar' => 'عين عريك'), 'postal_code' => 'P637'),
            array('city_id' => 10, 'name' => array('en' => 'Beit Ureik al-Fouqa', 'ar' => 'بيت عور الفوقا'), 'postal_code' => 'P638'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Tira', 'ar' => 'الطيرة'), 'postal_code' => 'P639'),
            array('city_id' => 10, 'name' => array('en' => 'Deir Dubwan', 'ar' => 'دير دبوان'), 'postal_code' => 'P640'),
            array('city_id' => 10, 'name' => array('en' => 'Deir Dubwan', 'ar' => 'دير دبوان'), 'postal_code' => 'P641'),
            array('city_id' => 10, 'name' => array('en' => 'Burqa', 'ar' => 'برقة'), 'postal_code' => 'P642'),
            array('city_id' => 10, 'name' => array('en' => 'Beitin', 'ar' => 'بيتين'), 'postal_code' => 'P643'),
            array('city_id' => 10, 'name' => array('en' => 'Ain Yabrud', 'ar' => 'عين يبرود'), 'postal_code' => 'P644'),
            array('city_id' => 10, 'name' => array('en' => 'Rammoun', 'ar' => 'رمون'), 'postal_code' => 'P645'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Tayba', 'ar' => 'الطيبة'), 'postal_code' => 'P646'),
            array('city_id' => 10, 'name' => array('en' => 'Deir Jarir', 'ar' => 'دير جرير'), 'postal_code' => 'P647'),
            array('city_id' => 10, 'name' => array('en' => 'Deir Jarir', 'ar' => 'دير جرير'), 'postal_code' => 'P648'),
            array('city_id' => 10, 'name' => array('en' => 'Badou al-Muarajat', 'ar' => 'بدو المعرجات'), 'postal_code' => 'P649'),
            array('city_id' => 10, 'name' => array('en' => 'Silwad', 'ar' => 'سلواد'), 'postal_code' => 'P650'),
            array('city_id' => 10, 'name' => array('en' => 'Silwad', 'ar' => 'سلواد'), 'postal_code' => 'P651'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Mazraa al-Sharqiya', 'ar' => 'المزرعة الشرقية'), 'postal_code' => 'P652'),
            array('city_id' => 10, 'name' => array('en' => 'Sinjel', 'ar' => 'سنجل'), 'postal_code' => 'P653'),
            array('city_id' => 10, 'name' => array('en' => 'Turmusayya', 'ar' => 'ترمسعيا'), 'postal_code' => 'P654'),
            array('city_id' => 10, 'name' => array('en' => 'Khirbet Abu Flah', 'ar' => 'خربة أبو فلاح'), 'postal_code' => 'P655'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Mughayir', 'ar' => 'المغير'), 'postal_code' => 'P657'),
            array('city_id' => 10, 'name' => array('en' => 'Bani Zaid al-Sharqiya', 'ar' => 'بني زيد الشرقية'), 'postal_code' => 'P660'),
            array('city_id' => 10, 'name' => array('en' => 'Qarawa Bani Zaid', 'ar' => 'قراوة بني زيد'), 'postal_code' => 'P661'),
            array('city_id' => 10, 'name' => array('en' => 'Kafr Ein', 'ar' => 'كفر عين'), 'postal_code' => 'P662'),
            array('city_id' => 10, 'name' => array('en' => 'Deir al-Sudan', 'ar' => 'دير السودان'), 'postal_code' => 'P663'),
            array('city_id' => 10, 'name' => array('en' => 'Ajjul', 'ar' => 'عجول'), 'postal_code' => 'P663'),
            array('city_id' => 10, 'name' => array('en' => 'Burham', 'ar' => 'برهام'), 'postal_code' => 'P664'),
            array('city_id' => 10, 'name' => array('en' => 'Umm Safa', 'ar' => 'أم صفا'), 'postal_code' => 'P664'),
            array('city_id' => 10, 'name' => array('en' => 'Jibya', 'ar' => 'جيبيا'), 'postal_code' => 'P664'),
            array('city_id' => 10, 'name' => array('en' => 'Kober', 'ar' => 'كوبر'), 'postal_code' => 'P665'),
            array('city_id' => 10, 'name' => array('en' => 'Rawabi', 'ar' => 'روابي'), 'postal_code' => 'P666'),
            array('city_id' => 10, 'name' => array('en' => 'Attara', 'ar' => 'عطارة'), 'postal_code' => 'P667'),
            array('city_id' => 10, 'name' => array('en' => 'Abwein', 'ar' => 'عبوين'), 'postal_code' => 'P668'),
            array('city_id' => 10, 'name' => array('en' => 'Jiljilia', 'ar' => 'جلجيليا'), 'postal_code' => 'P669'),
            array('city_id' => 10, 'name' => array('en' => 'Ittihad', 'ar' => 'الاتحاد'), 'postal_code' => 'P670'),
            array('city_id' => 10, 'name' => array('en' => 'Deir Ammar Refugee Camp', 'ar' => 'مخيم دير عمار'), 'postal_code' => 'P672'),
            array('city_id' => 10, 'name' => array('en' => 'Deir Abu Mashal', 'ar' => 'دير أبو مشعل'), 'postal_code' => 'P673'),
            array('city_id' => 10, 'name' => array('en' => 'Aaboud', 'ar' => 'عابود'), 'postal_code' => 'P674'),
            array('city_id' => 10, 'name' => array('en' => 'Rantis', 'ar' => 'رنتيس'), 'postal_code' => 'P675'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Lubban al-Gharbi', 'ar' => 'اللبن الغربي'), 'postal_code' => 'P676'),
            array('city_id' => 10, 'name' => array('en' => 'Bani Zaid', 'ar' => 'بني زيد'), 'postal_code' => 'P677'),
            array('city_id' => 10, 'name' => array('en' => 'Nabi Saleh', 'ar' => 'النبي صالح'), 'postal_code' => 'P678'),
            array('city_id' => 10, 'name' => array('en' => 'Deir Nizam', 'ar' => 'دير نظام'), 'postal_code' => 'P679'),
            array('city_id' => 10, 'name' => array('en' => 'Nilin', 'ar' => 'نعلين'), 'postal_code' => 'P680'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Midya', 'ar' => 'المدية'), 'postal_code' => 'P681'),
            array('city_id' => 10, 'name' => array('en' => 'Budrus', 'ar' => 'بدرس'), 'postal_code' => 'P682'),
            array('city_id' => 10, 'name' => array('en' => 'Qibya', 'ar' => 'قبيه'), 'postal_code' => 'P683'),
            array('city_id' => 10, 'name' => array('en' => 'Shuqba', 'ar' => 'شقبا'), 'postal_code' => 'P684'),
            array('city_id' => 10, 'name' => array('en' => 'Deir Qidiss', 'ar' => 'دير قديس'), 'postal_code' => 'P685'),
            array('city_id' => 10, 'name' => array('en' => 'Shibteen', 'ar' => 'شبتين'), 'postal_code' => 'P685'),
            array('city_id' => 10, 'name' => array('en' => 'Kharbatha Bani Harith', 'ar' => 'خربثا بني حارث'), 'postal_code' => 'P686'),
            array('city_id' => 10, 'name' => array('en' => 'Bilin', 'ar' => 'بلعين'), 'postal_code' => 'P687'),
            array('city_id' => 10, 'name' => array('en' => 'Kafr Nima', 'ar' => 'كفر نعمة'), 'postal_code' => 'P688'),
            array('city_id' => 10, 'name' => array('en' => 'Al-Janiya', 'ar' => 'الجانية'), 'postal_code' => 'P689'),
            array('city_id' => 10, 'name' => array('en' => 'Ras Karkar', 'ar' => 'راس كركر'), 'postal_code' => 'P689'),
            array('city_id' => 10, 'name' => array('en' => 'Beit Liqya', 'ar' => 'بيت لقيا'), 'postal_code' => 'P690'),
            array('city_id' => 10, 'name' => array('en' => 'Beit Nuba', 'ar' => 'بيت نوبا'), 'postal_code' => 'P692'),
            array('city_id' => 10, 'name' => array('en' => 'Beit Sira', 'ar' => 'بيت سيرا'), 'postal_code' => 'P693'),
            array('city_id' => 10, 'name' => array('en' => 'Kharbatha al-Misbah', 'ar' => 'خربثا المصباح'), 'postal_code' => 'P694'),
            array('city_id' => 10, 'name' => array('en' => 'Beit Ura al-Tahta', 'ar' => 'بيت عور التحتا'), 'postal_code' => 'P696'),
            array('city_id' => 10, 'name' => array('en' => 'Deir Ebzia', 'ar' => 'دير إبزيع'), 'postal_code' => 'P698'),
            array('city_id' => 10, 'name' => array('en' => 'Saffa', 'ar' => 'صفا'), 'postal_code' => 'P699'),

            // الخليل

            array('city_id' => 11, 'name' => array('en' => 'Hebron', 'ar' => 'الخليل'), 'postal_code' => 'P700'),
            array('city_id' => 11, 'name' => array('en' => 'Qila', 'ar' => 'قلاع زيتا'), 'postal_code' => 'P719'),
            array('city_id' => 11, 'name' => array('en' => 'Al-Buwayra (Aqabat Injila)', 'ar' => 'البويره (عقبة انجيله)'), 'postal_code' => 'P728'),
            array('city_id' => 11, 'name' => array('en' => 'Khallet al-Dar', 'ar' => 'خلة الدار'), 'postal_code' => 'P728'),
            array('city_id' => 11, 'name' => array('en' => 'Qalqas', 'ar' => 'قلقس'), 'postal_code' => 'P729'),
            array('city_id' => 11, 'name' => array('en' => 'Sa\'ir', 'ar' => 'سعير'), 'postal_code' => 'P730'),
            array('city_id' => 11, 'name' => array('en' => 'Hamrush', 'ar' => 'حمروش'), 'postal_code' => 'P730'),
            array('city_id' => 11, 'name' => array('en' => 'Umm al-Batum', 'ar' => 'أم البطم'), 'postal_code' => 'P730'),
            array('city_id' => 11, 'name' => array('en' => 'Ash-Shuyukh', 'ar' => 'الشيوخ'), 'postal_code' => 'P732'),
            array('city_id' => 11, 'name' => array('en' => 'Beit Einun', 'ar' => 'بيت عينون'), 'postal_code' => 'P733'),
            array('city_id' => 11, 'name' => array('en' => 'Al-Buq\'a', 'ar' => 'البقعه'), 'postal_code' => 'P733'),
            array('city_id' => 11, 'name' => array('en' => 'Al-Buwayb', 'ar' => 'البويب'), 'postal_code' => 'P734'),
            array('city_id' => 11, 'name' => array('en' => 'Bani Na\'im', 'ar' => 'بني نعيم'), 'postal_code' => 'P734'),
            array('city_id' => 11, 'name' => array('en' => 'Khallet al-Maiyya', 'ar' => 'خلة المية'), 'postal_code' => 'P737'),
            array('city_id' => 11, 'name' => array('en' => 'Khirbet al-Dair', 'ar' => 'خربة الدير'), 'postal_code' => 'P748'),
            array('city_id' => 11, 'name' => array('en' => 'Tarqumiya', 'ar' => 'ترقوميا'), 'postal_code' => 'P750'),
            array('city_id' => 11, 'name' => array('en' => 'Idhna', 'ar' => 'إذنا'), 'postal_code' => 'P751'),
            array('city_id' => 11, 'name' => array('en' => 'Taffuh', 'ar' => 'تفوح'), 'postal_code' => 'P753'),
            array('city_id' => 11, 'name' => array('en' => 'Beit Kahil', 'ar' => 'بيت كاحل'), 'postal_code' => 'P755'),
            array('city_id' => 11, 'name' => array('en' => 'Beit Ula', 'ar' => 'بيت أولا'), 'postal_code' => 'P756'),
            array('city_id' => 11, 'name' => array('en' => 'Nuba', 'ar' => 'نوبا'), 'postal_code' => 'P758'),
            array('city_id' => 11, 'name' => array('en' => 'Hatta', 'ar' => 'حتا'), 'postal_code' => 'P758'),
            array('city_id' => 11, 'name' => array('en' => 'Kharas', 'ar' => 'خاراس'), 'postal_code' => 'P759'),
            array('city_id' => 11, 'name' => array('en' => 'Beit Maqdum', 'ar' => 'بيت مقدوم'), 'postal_code' => 'P763'),
            array('city_id' => 11, 'name' => array('en' => 'Deir Samit', 'ar' => 'دير سامت'), 'postal_code' => 'P764'),
            array('city_id' => 11, 'name' => array('en' => 'Beit Awwa', 'ar' => 'بيت عوا'), 'postal_code' => 'P766'),
            array('city_id' => 11, 'name' => array('en' => 'Sikka', 'ar' => 'سكة'), 'postal_code' => 'P767'),
            array('city_id' => 11, 'name' => array('en' => 'Al-Majd', 'ar' => 'المجد'), 'postal_code' => 'P767'),
            array('city_id' => 11, 'name' => array('en' => 'Deir al-\'Asal al-Tahta', 'ar' => 'دير العسل التحتا'), 'postal_code' => 'P768'),
            array('city_id' => 11, 'name' => array('en' => 'Deir al-\'Asal al-Fawqa', 'ar' => 'دير العسل الفوقا'), 'postal_code' => 'P768'),
            array('city_id' => 11, 'name' => array('en' => 'Beit ar-Rush al-Tahta', 'ar' => 'بيت الروش التحتا'), 'postal_code' => 'P768'),
            array('city_id' => 11, 'name' => array('en' => 'Wadi al-Kilab', 'ar' => 'وادي الكلاب'), 'postal_code' => 'P769'),
            array('city_id' => 11, 'name' => array('en' => 'Beit ar-Rush al-Fawqa', 'ar' => 'بيت الروش الفوقا'), 'postal_code' => 'P769'),
            array('city_id' => 11, 'name' => array('en' => 'Beit Mirsim', 'ar' => 'بيت مرسم'), 'postal_code' => 'P769'),
            array('city_id' => 11, 'name' => array('en' => 'Dura', 'ar' => 'دورا'), 'postal_code' => 'P770'),
            array('city_id' => 11, 'name' => array('en' => 'Khirbet Salama', 'ar' => 'خربة سلامة'), 'postal_code' => 'P774'),
            array('city_id' => 11, 'name' => array('en' => 'Wadi Ubaid', 'ar' => 'وادي عبيد'), 'postal_code' => 'P774'),
            array('city_id' => 11, 'name' => array('en' => 'Faqiqis', 'ar' => 'فقيقيس'), 'postal_code' => 'P774'),
            array('city_id' => 11, 'name' => array('en' => 'Khursa', 'ar' => 'خرسا'), 'postal_code' => 'P774'),
            array('city_id' => 11, 'name' => array('en' => 'Marah al-Baqqar', 'ar' => 'مراح البقار'), 'postal_code' => 'P775'),
            array('city_id' => 11, 'name' => array('en' => 'As-Sura', 'ar' => 'الصرة'), 'postal_code' => 'P775'),
            array('city_id' => 11, 'name' => array('en' => 'Khallet al-\'Aqd', 'ar' => 'خلة العقد'), 'postal_code' => 'P775'),
            array('city_id' => 11, 'name' => array('en' => 'Imreish', 'ar' => 'إمريش'), 'postal_code' => 'P775'),
            array('city_id' => 11, 'name' => array('en' => 'Kurza', 'ar' => 'كرزة'), 'postal_code' => 'P776'),
            array('city_id' => 11, 'name' => array('en' => 'Rabud', 'ar' => 'رابود'), 'postal_code' => 'P776'),
            array('city_id' => 11, 'name' => array('en' => 'Hadab al-\'Alaqa', 'ar' => 'حدب العلقة'), 'postal_code' => 'P776'),
            array('city_id' => 11, 'name' => array('en' => 'Adh-Dhahiriya', 'ar' => 'الظاهرية'), 'postal_code' => 'P776'),
            array('city_id' => 11, 'name' => array('en' => 'Karma', 'ar' => 'كرمة'), 'postal_code' => 'P777'),
            array('city_id' => 11, 'name' => array('en' => 'Beit Amra', 'ar' => 'بيت عمرة'), 'postal_code' => 'P777'),
            array('city_id' => 11, 'name' => array('en' => 'Tarrama', 'ar' => 'طرامة'), 'postal_code' => 'P778'),
            array('city_id' => 11, 'name' => array('en' => 'Hadab al-Fawwar', 'ar' => 'حدب ألفوار'), 'postal_code' => 'P778'),
            array('city_id' => 11, 'name' => array('en' => 'Wadi ash-Shajina', 'ar' => 'وادي الشاجنة'), 'postal_code' => 'P778'),
            array('city_id' => 11, 'name' => array('en' => 'Deir Razih', 'ar' => 'دير رازح'), 'postal_code' => 'P778'),
            array('city_id' => 11, 'name' => array('en' => 'Al-Fawwar Camp', 'ar' => 'مخيم الفوار'), 'postal_code' => 'P779'),
            array('city_id' => 11, 'name' => array('en' => 'Yatta', 'ar' => 'يطا'), 'postal_code' => 'P780'),
            array('city_id' => 11, 'name' => array('en' => 'Yatta', 'ar' => 'يطا'), 'postal_code' => 'P781'),
            array('city_id' => 11, 'name' => array('en' => 'Yatta', 'ar' => 'يطا'), 'postal_code' => 'P782'),
            array('city_id' => 11, 'name' => array('en' => 'Yatta', 'ar' => 'يطا'), 'postal_code' => 'P783'),
            array('city_id' => 11, 'name' => array('en' => 'Umm al-\'Amad (Sahl Wadi al-Maa)', 'ar' => 'أم العمد (سهل واد الماء)'), 'postal_code' => 'P785'),
            array('city_id' => 11, 'name' => array('en' => 'Yatta', 'ar' => 'يطا'), 'postal_code' => 'P785'),
            array('city_id' => 11, 'name' => array('en' => 'Zif', 'ar' => 'زيف'), 'postal_code' => 'P785'),
            array('city_id' => 11, 'name' => array('en' => 'Umm ash-Shaqhan', 'ar' => 'أم الشقحان'), 'postal_code' => 'P785'),
            array('city_id' => 11, 'name' => array('en' => 'Al-Heila', 'ar' => 'الحيلة'), 'postal_code' => 'P786'),
            array('city_id' => 11, 'name' => array('en' => 'Yatta', 'ar' => 'يطا'), 'postal_code' => 'P787'),
            array('city_id' => 11, 'name' => array('en' => 'Ar-Rihiya', 'ar' => 'الريحية'), 'postal_code' => 'P788'),
            array('city_id' => 11, 'name' => array('en' => 'Adh-Dhahiriya', 'ar' => 'الظاهرية'), 'postal_code' => 'P790'),
            array('city_id' => 11, 'name' => array('en' => 'Adh-Dhahiriya', 'ar' => 'الظاهرية'), 'postal_code' => 'P791'),
            array('city_id' => 11, 'name' => array('en' => 'Adh-Dhahiriya', 'ar' => 'الظاهرية'), 'postal_code' => 'P792'),
            array('city_id' => 11, 'name' => array('en' => 'Adh-Dhahiriya', 'ar' => 'الظاهرية'), 'postal_code' => 'P793'),
            array('city_id' => 11, 'name' => array('en' => 'Adh-Dhahiriya', 'ar' => 'الظاهرية'), 'postal_code' => 'P794'),
            array('city_id' => 11, 'name' => array('en' => 'Al-Burj (including al-Birah)', 'ar' => 'البرج تشمل البيرة'), 'postal_code' => 'P795'),
            array('city_id' => 11, 'name' => array('en' => 'Innab al-Kabir', 'ar' => 'عناب الكبير'), 'postal_code' => 'P796'),
            array('city_id' => 11, 'name' => array('en' => 'Ar-Ramadin', 'ar' => 'الرماضين'), 'postal_code' => 'P796'),
            array('city_id' => 11, 'name' => array('en' => 'Arab al-Fureijat', 'ar' => 'عرب الفريجات'), 'postal_code' => 'P796'),
            array('city_id' => 11, 'name' => array('en' => 'Wadi al-Amayir', 'ar' => 'وادي العماير'), 'postal_code' => 'P797'),
            array('city_id' => 11, 'name' => array('en' => 'As-Samu\'', 'ar' => 'السموع'), 'postal_code' => 'P797'),
            array('city_id' => 11, 'name' => array('en' => 'Imneizil', 'ar' => 'إمنيزل'), 'postal_code' => 'P797'),
            array('city_id' => 11, 'name' => array('en' => 'Khirbet Zanuta', 'ar' => 'خربة زنوتة'), 'postal_code' => 'P797'),

            //شمال غزة

            array('city_id' => 12, 'name' => array('en' => 'Beit Lahia', 'ar' => 'بيت لاهيا'), 'postal_code' => 'P800'),
            array('city_id' => 12, 'name' => array('en' => 'Umm an-Nasr (Al-Qarya al-Badawiyya al-Maslak)', 'ar' => 'أم النصر (القرية البدوية المسلخ)'), 'postal_code' => 'P810'),
            array('city_id' => 12, 'name' => array('en' => 'Beit Hanoun', 'ar' => 'بيت حانون'), 'postal_code' => 'P810'),
            array('city_id' => 12, 'name' => array('en' => 'Jabalia Camp', 'ar' => 'مخيم جباليا'), 'postal_code' => 'P819'),
            array('city_id' => 12, 'name' => array('en' => 'Jabalia', 'ar' => 'جباليا'), 'postal_code' => 'P820'),
            array('city_id' => 12, 'name' => array('en' => 'Jabalia', 'ar' => 'جباليا'), 'postal_code' => 'P830'),

            //غزة

            array('city_id' => 13, 'name' => array('en' => 'Gaza (Including Al-Awda City)', 'ar' => 'غزة (تشمل مدينة العودة)'), 'postal_code' => 'P840'),
            array('city_id' => 13, 'name' => array('en' => 'Beach Camp', 'ar' => 'مخيم الشاطىء'), 'postal_code' => 'P849'),
            array('city_id' => 13, 'name' => array('en' => 'Gaza (Including Al-Awda City)', 'ar' => 'غزة (تشمل مدينة العودة)'), 'postal_code' => 'P850'),
            array('city_id' => 13, 'name' => array('en' => 'Gaza (Including Al-Awda City)', 'ar' => 'غزة (تشمل مدينة العودة)'), 'postal_code' => 'P860'),
            array('city_id' => 13, 'name' => array('en' => 'Gaza (Including Al-Awda City)', 'ar' => 'غزة (تشمل مدينة العودة)'), 'postal_code' => 'P870'),
            array('city_id' => 13, 'name' => array('en' => 'Juhor ad-Dik', 'ar' => 'جحر الديك'), 'postal_code' => 'P880'),
            array('city_id' => 13, 'name' => array('en' => 'Gaza (Including Al-Awda City)', 'ar' => 'غزة (تشمل مدينة العودة)'), 'postal_code' => 'P880'),
            array('city_id' => 13, 'name' => array('en' => 'Al-Mughraka (Abu Mideen)', 'ar' => 'المغراقه (ابو مدين)'), 'postal_code' => 'P890'),
            array('city_id' => 13, 'name' => array('en' => 'Al-Zahraa City', 'ar' => 'مدينة الزهراء'), 'postal_code' => 'P890'),

            // دير البلح

            array('city_id' => 14, 'name' => array('en' => 'An-Nuseirat', 'ar' => 'النصيرات'), 'postal_code' => 'P900'),
            array('city_id' => 14, 'name' => array('en' => 'Al-Bureij', 'ar' => 'البريج'), 'postal_code' => 'P900'),
            array('city_id' => 14, 'name' => array('en' => 'Al-Bureij Camp', 'ar' => 'مخيم البريج'), 'postal_code' => 'P905'),
            array('city_id' => 14, 'name' => array('en' => 'An-Nuseirat Camp', 'ar' => 'مخيم النصيرات'), 'postal_code' => 'P909'),
            array('city_id' => 14, 'name' => array('en' => 'Az-Zawayda', 'ar' => 'الزوايدة'), 'postal_code' => 'P910'),
            array('city_id' => 14, 'name' => array('en' => 'Al-Musaddar', 'ar' => 'المصدر'), 'postal_code' => 'P910'),
            array('city_id' => 14, 'name' => array('en' => 'Al-Maghazi', 'ar' => 'المغازي'), 'postal_code' => 'P910'),
            array('city_id' => 14, 'name' => array('en' => 'Al-Maghazi Camp', 'ar' => 'مخيم المغازي'), 'postal_code' => 'P919'),
            array('city_id' => 14, 'name' => array('en' => 'Deir al-Balah', 'ar' => 'دير البلح'), 'postal_code' => 'P920'),
            array('city_id' => 14, 'name' => array('en' => 'Wadi as-Salqa', 'ar' => 'وادي السلقا'), 'postal_code' => 'P920'),
            array('city_id' => 14, 'name' => array('en' => 'Deir al-Balah Camp', 'ar' => 'مخيم دير البلح'), 'postal_code' => 'P929'),

            // خانيونس

            array('city_id' => 15, 'name' => array('en' => 'Al-Qarara', 'ar' => 'القرارة'), 'postal_code' => 'P930'),
            array('city_id' => 15, 'name' => array('en' => 'Khan Yunis', 'ar' => 'خانيونس'), 'postal_code' => 'P930'),
            array('city_id' => 15, 'name' => array('en' => 'Bani Suhaila', 'ar' => 'بني سهيلا'), 'postal_code' => 'P940'),
            array('city_id' => 15, 'name' => array('en' => 'Abasan al-Jadida (Al-Saghira)', 'ar' => 'عبسان الجديدة (الصغيرة )'), 'postal_code' => 'P940'),
            array('city_id' => 15, 'name' => array('en' => 'Abasan al-Kabira', 'ar' => 'عبسان الكبيرة'), 'postal_code' => 'P940'),
            array('city_id' => 15, 'name' => array('en' => 'Khuzaa', 'ar' => 'خزاعة'), 'postal_code' => 'P940'),
            array('city_id' => 15, 'name' => array('en' => 'Khan Yunis', 'ar' => 'خانيونس'), 'postal_code' => 'P950'),
            array('city_id' => 15, 'name' => array('en' => 'Khan Yunis', 'ar' => 'خانيونس'), 'postal_code' => 'P960'),
            array('city_id' => 15, 'name' => array('en' => 'Al-Fukhari', 'ar' => 'الفخاري'), 'postal_code' => 'P960'),
            array('city_id' => 15, 'name' => array('en' => 'Khan Yunis Camp', 'ar' => 'مخيم خانيونس'), 'postal_code' => 'P969'),

            //رفح

            array('city_id' => 16, 'name' => array('en' => 'Rafah', 'ar' => 'رفح'), 'postal_code' => 'P970'),
            array('city_id' => 16, 'name' => array('en' => 'Rafah', 'ar' => 'رفح'), 'postal_code' => 'P980'),
            array('city_id' => 16, 'name' => array('en' => 'Al-Nasr (Al-Bayouk)', 'ar' => 'النصر (البيوك)'), 'postal_code' => 'P990'),
            array('city_id' => 16, 'name' => array('en' => 'Shouka al-Sufi', 'ar' => 'شوكة الصوفي'), 'postal_code' => 'P990'),
            array('city_id' => 16, 'name' => array('en' => 'Rafah Camp', 'ar' => 'مخيم رفح'), 'postal_code' => 'P999'),
        );

        foreach ($neighborhoods as $neighborhood) {
            Neighborhood::create($neighborhood);
        }

    }
}
